name: 'Install dependencies'
description: 'Set environment and install dependencies'
inputs:
  targets:
    description: 'Rust target triple(s) to install'
    required: false
    default: 'x86_64-unknown-linux-gnu'
runs:
  using: composite
  steps:
    - name: Install Rust 🦀
      uses: dtolnay/rust-toolchain@7e38f4b43b4db5c8dd498af069a4f6196df1d067 # master 2026-10-01
      with:
        toolchain: stable
        targets: ${{ inputs.targets }}

    - name: Run sccache-cache
      uses: mozilla-actions/sccache-action@fc920bf0ec8de6ee65d409111f7ec508035751ba # v0.0.11
