name: 'Install dependencies'
description: 'Set environment and install dependencies'
runs:
  using: composite
  steps:
    - name: Install Rust 🦀
      uses: dtolnay/rust-toolchain@stable

    - name: Run sccache-cache
      uses: mozilla-actions/sccache-action@v0.0.9
